//
//  Friend.swift
//  CodeNameKindness
//
//  Created by Luca Haar on 26/7/2024.
//

import Foundation
import FirebaseFirestore

class Friend {
    var id: String!
    var agentName: String
    var level: Int
    var badges: [String]
    
    // default init, it will be used whenever we want to add a friend
    // therefore we won't know the id as it's autogenerated by firestore
    init(agentName: String, level: Int, badges: [String]) {
        self.agentName = agentName
        self.level = level
        self.badges = badges
    }

    // this initializer will be used whenever we fetch a friend from the db (usually via a query so we get a batch of friends),
    // an existing agent has already an autogenerated id
    convenience init(id: String, agentName: String, level: Int, badges: [String]) {
        self.init(agentName: agentName, level: level, badges: badges)
        self.id = id
    }

    // this initializer will be used whenever we want to fetch a friend from the database by id,
    // we know the autogenerated id before hand, but none of the other fields
    convenience init(id: String) {
        self.init(agentName: "", level: 1, badges: [String]())
        self.id = id
    }

    // this initializer is very handy when we work with firestore,
    // as firestore retrieves the data in a dictionary
    convenience init(id: String, dictionary: [String: Any]) {
        // the dictionary stores String as keys ("firstname", "lastname", etc)
        // the values data-types varies depending on the property, that's why we indicate Any
        self.init(
                  id: id,
                  agentName: dictionary["agentName"] as! String,
                  level: dictionary["level"] as! Int,
                  badges: dictionary["badges"] as! [String],
                )
    }
}
