//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceLibrarySystem {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int UserLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((this.UserLevelField.Equals(value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap")]
    public interface WebServiceLibrarySystemSoap {
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse GetAllUsers(Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse> GetAllUsersAsync(Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(Controller.ServiceReferenceLibrarySystem.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(Controller.ServiceReferenceLibrarySystem.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceLibrarySystem.User[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(Controller.ServiceReferenceLibrarySystem.User[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLibrarySystemSoapChannel : Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLibrarySystemSoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap>, Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap {
        
        public WebServiceLibrarySystemSoapClient() {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySystemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.GetAllUsers(Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public Controller.ServiceReferenceLibrarySystem.User[] GetAllUsers() {
            Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest inValue = new Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.GetAllUsersRequestBody();
            Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse retVal = ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse> Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.GetAllUsersAsync(Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetAllUsersResponse> GetAllUsersAsync() {
            Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest inValue = new Controller.ServiceReferenceLibrarySystem.GetAllUsersRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.GetAllUsersRequestBody();
            return ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).GetAllUsersAsync(inValue);
        }
    }
}
