//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceLibrarySystem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap")]
    public interface WebServiceLibrarySystemSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Controller.ServiceReferenceLibrarySystem.HelloWorldResponse HelloWorld(Controller.ServiceReferenceLibrarySystem.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.HelloWorldResponse> HelloWorldAsync(Controller.ServiceReferenceLibrarySystem.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        Controller.ServiceReferenceLibrarySystem.GetUserResponse GetUser(Controller.ServiceReferenceLibrarySystem.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetUserResponse> GetUserAsync(Controller.ServiceReferenceLibrarySystem.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name TestFuncResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestFunc", ReplyAction="*")]
        Controller.ServiceReferenceLibrarySystem.TestFuncResponse TestFunc(Controller.ServiceReferenceLibrarySystem.TestFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.TestFuncResponse> TestFuncAsync(Controller.ServiceReferenceLibrarySystem.TestFuncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Controller.ServiceReferenceLibrarySystem.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Controller.ServiceReferenceLibrarySystem.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(Controller.ServiceReferenceLibrarySystem.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int uid;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(int uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(Controller.ServiceReferenceLibrarySystem.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(string GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFunc", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.TestFuncRequestBody Body;
        
        public TestFuncRequest() {
        }
        
        public TestFuncRequest(Controller.ServiceReferenceLibrarySystem.TestFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int no1;
        
        public TestFuncRequestBody() {
        }
        
        public TestFuncRequestBody(int no1) {
            this.no1 = no1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFuncResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLibrarySystem.TestFuncResponseBody Body;
        
        public TestFuncResponse() {
        }
        
        public TestFuncResponse(Controller.ServiceReferenceLibrarySystem.TestFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestFuncResult;
        
        public TestFuncResponseBody() {
        }
        
        public TestFuncResponseBody(string TestFuncResult) {
            this.TestFuncResult = TestFuncResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLibrarySystemSoapChannel : Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLibrarySystemSoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap>, Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap {
        
        public WebServiceLibrarySystemSoapClient() {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySystemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySystemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLibrarySystem.HelloWorldResponse Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.HelloWorld(Controller.ServiceReferenceLibrarySystem.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Controller.ServiceReferenceLibrarySystem.HelloWorldRequest inValue = new Controller.ServiceReferenceLibrarySystem.HelloWorldRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.HelloWorldRequestBody();
            Controller.ServiceReferenceLibrarySystem.HelloWorldResponse retVal = ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.HelloWorldResponse> Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.HelloWorldAsync(Controller.ServiceReferenceLibrarySystem.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.HelloWorldResponse> HelloWorldAsync() {
            Controller.ServiceReferenceLibrarySystem.HelloWorldRequest inValue = new Controller.ServiceReferenceLibrarySystem.HelloWorldRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.HelloWorldRequestBody();
            return ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLibrarySystem.GetUserResponse Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.GetUser(Controller.ServiceReferenceLibrarySystem.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public string GetUser(int uid) {
            Controller.ServiceReferenceLibrarySystem.GetUserRequest inValue = new Controller.ServiceReferenceLibrarySystem.GetUserRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.GetUserRequestBody();
            inValue.Body.uid = uid;
            Controller.ServiceReferenceLibrarySystem.GetUserResponse retVal = ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetUserResponse> Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.GetUserAsync(Controller.ServiceReferenceLibrarySystem.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.GetUserResponse> GetUserAsync(int uid) {
            Controller.ServiceReferenceLibrarySystem.GetUserRequest inValue = new Controller.ServiceReferenceLibrarySystem.GetUserRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.GetUserRequestBody();
            inValue.Body.uid = uid;
            return ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLibrarySystem.TestFuncResponse Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.TestFunc(Controller.ServiceReferenceLibrarySystem.TestFuncRequest request) {
            return base.Channel.TestFunc(request);
        }
        
        public string TestFunc(int no1) {
            Controller.ServiceReferenceLibrarySystem.TestFuncRequest inValue = new Controller.ServiceReferenceLibrarySystem.TestFuncRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.TestFuncRequestBody();
            inValue.Body.no1 = no1;
            Controller.ServiceReferenceLibrarySystem.TestFuncResponse retVal = ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).TestFunc(inValue);
            return retVal.Body.TestFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.TestFuncResponse> Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap.TestFuncAsync(Controller.ServiceReferenceLibrarySystem.TestFuncRequest request) {
            return base.Channel.TestFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLibrarySystem.TestFuncResponse> TestFuncAsync(int no1) {
            Controller.ServiceReferenceLibrarySystem.TestFuncRequest inValue = new Controller.ServiceReferenceLibrarySystem.TestFuncRequest();
            inValue.Body = new Controller.ServiceReferenceLibrarySystem.TestFuncRequestBody();
            inValue.Body.no1 = no1;
            return ((Controller.ServiceReferenceLibrarySystem.WebServiceLibrarySystemSoap)(this)).TestFuncAsync(inValue);
        }
    }
}
